# Generated by Django 4.0.5 on 2022-06-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_pv_modules_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='pv_modules_power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_id', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pv_modules',
            name='modules_id',
            field=models.CharField(default='03.PVM', max_length=50),
        ),
        migrations.AlterField(
            model_name='pv_modules',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pv_modules',
            name='power_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_modules', to='procurement.pv_modules_power'),
        ),
    ]
