# Generated by Django 4.0.5 on 2022-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_inventory_pv_modules_price_cif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pv_module_brand',
            name='brand_id',
            field=models.CharField(max_length=10),
        ),
    ]
