# Generated by Django 4.0.5 on 2022-06-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_pv_module_brand_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pv_modules',
            old_name='price_DPP',
            new_name='price_DDP',
        ),
        migrations.AddField(
            model_name='pv_module_brand',
            name='vendor_contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
