# Generated by Django 4.0.4 on 2022-06-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_inverters_brand_inverters_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inv_acessorie_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inverter_acessories',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inverter_acessories',
            name='vendor',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='vendor_contact',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='vendor_email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='vendor_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inverter_acessories',
            name='acessorie_id',
            field=models.CharField(default='05.ACC-01', max_length=50),
        ),
        migrations.AlterField(
            model_name='inverter_acessories',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_acessories', to='procurement.brand'),
        ),
        migrations.AlterField(
            model_name='inverter_acessories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inverter_acessories',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_acessories', to='procurement.inv_acessorie_type'),
        ),
    ]
