# Generated by Django 4.0.4 on 2022-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_inv_acessorie_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter_acessories',
            name='payment_conditions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
