# Generated by Django 4.0.4 on 2022-06-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_inverter_acessories_payment_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand_acessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_contact', models.CharField(max_length=100)),
                ('vendor_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='inverter_acessories',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_acessories', to='procurement.brand_acessories'),
        ),
    ]
