# Generated by Django 4.0.4 on 2022-06-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_brand_cables_cables'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cables',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='cable_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_id', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=80)),
                ('type_cable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_cabo', to='procurement.type_cable')),
            ],
        ),
        migrations.AddField(
            model_name='cables',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_cables', to='procurement.cable_information'),
        ),
        migrations.AddField(
            model_name='cables',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_cables', to='procurement.type_cable'),
        ),
    ]
